window.PROJECT_JSON_DATA={
	"填寫說明" : [
		{
			"Name":  "建案名稱",
			"Address":"建案地址",
			"Map":"Google map 能搜尋到的名稱 or 經緯度",
			"StartYear":  "開工年度",
			"FinishYear":  "完工年度",
			"Design":"設計單位",
			"Owner":"業主單位",
			"ImagePath": "Image/BuildCase/資料夾路徑",
			"Image_Description": [ "0.jpg_文字描述 -> 【可以整列不填，自動不顯示描述】" ],
			"ShowImage": "0.jpg -> 【只能填寫單張】",
			"Image": [ "0-6.jpg", "7.png", "-> 【支援多張填寫、支援多張縮寫】" ],
			"Image_Video": [ "影片 ID" ],
			"Type": "build、landscape、decoration、plant、cement、sport、wood、temple、historicSite、greenbuild",
			"Position": "台北、桃園、新竹、苗栗、台中、彰化、南投、雲林、嘉義、台南、高雄、屏東、宜蘭、花蓮、台東、澎湖、小琉球、金門、馬祖、蘭嶼、綠島",
			"Price": 900,
			"Wonderful": "no",
			"Display": "true -> 【填寫 fales 不顯示】"
		}
	],
	"ID"     : "Project",
	"ProjectList" : [
					{
						"Name":  "屏東縣獅子鄉楓林國小教室新建工程",
						"Address":"屏東縣獅子鄉楓林二巷22-2號",
						"Map":"楓林國小",
						"StartYear":  "76",
						"FinishYear":  "77",
						"Design":"吳大朝建築師事務所",
						"Owner":"屏東縣楓林國小",
						"ImagePath": "1_屏東縣獅子鄉楓林國小新建工程",
						"Image_Description": [ "0.jpg_測試測試" ],
						"ShowImage": "0.jpg",
						"Image": [ "0-6.jpg" ],
						"Type": "build",
						"Position": "屏東",
						"Price": 900,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "墾丁國家公園梅花鹿復育計畫研究站新建工程",
						"Address":"屏東縣恆春鎮墾丁路596號",
						"Map":"墾丁國家公園",
						"StartYear":  "76",
						"FinishYear":  "77",
						"Design":"許仲川建築師事務所",
						"Owner":"墾丁國家公園管理處",
						"ImagePath": "3_梅花鹿復育計畫研究站",
						"ShowImage": "0.jpg",
						"Image": [ "0.jpg" ],
						"Type": "build",
						"Position": "屏東",
						"Price": 900,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "墾丁國家公園社頂公園公廁新建工程",
						"Address":"屏東縣恆春鎮社興路186-1號 (墾丁牌樓往森林遊樂區方向後)",
						"Map":"社頂自然公園",
						"StartYear":  "76",
						"FinishYear":  "77",
						"Design":"宗邁建築師事務所",
						"Owner":"墾丁國家公園管理處",
						"ImagePath": "4_墾丁國家公園_社頂公園公廁新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-8.jpg" ],
						"Type": "build",
						"Position": "屏東",
						"Price": 211,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "墾丁國家公園管理處石牛溪公共設施工程",
						"Address":"屏東縣恆春鎮墾丁路596號",
						"Map":"墾丁國家公園",
						"StartYear":  "77",
						"FinishYear":  "77",
						"Design":"",
						"Owner":"墾丁國家公園管理處",
						"ImagePath": "7_墾丁國家公園管理處石牛溪公共設施工程",
						"ShowImage": "0.jpg",
						"Image": [ "0.jpg" ],
						"Type": "build",
						"Position": "屏東",
						"Price": 900,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "墾丁國家公園管理處小灣服務站第一、三期工程",
						"Address":"屏東縣恆春鎮墾丁路14號",
						"Map":"小灣遊客服務中心",
						"StartYear":  "77",
						"FinishYear":  "81",
						"Design":"宗邁建築師事務所",
						"Owner":"墾丁國家公園管理處",
						"ImagePath": "12_小灣服務站",
						"ShowImage": "0.jpg",
						"Image": [ "0-3.jpg" ],
						"Type": "build",
						"Position": "屏東",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "墾丁國家公園管理處社頂公園涼亭平台第二期工程",
						"Address":"屏東縣恆春鎮社興路186-1號 (墾丁牌樓往森林遊樂區方向後)",
						"Map":"社頂自然公園",
						"StartYear":  "77",
						"FinishYear":  "77",
						"Design":"李重耀建築師事務所",
						"Owner":"墾丁國家公園管理處",
						"ImagePath": "10_墾丁國家公園_社頂公園涼亭平台第二期工程",
						"ShowImage": "0.jpg",
						"Image": [ "2-13.jpg" ],
						"Image_360": [ "0-1.jpg" ],
						"Type": "wood",
						"Position": "屏東",
						"Price": 724,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "墾丁國家公園管理處社頂停車場.賣店新建工程",
						"Address":"屏東縣恆春鎮社興路186-1號 (墾丁牌樓往森林遊樂區方向後)",
						"Map":"社頂自然公園管理站",
						"StartYear":  "78",
						"FinishYear":  "80",
						"Design":"吳忠寬建築師事務所",
						"Owner":"墾丁國家公園管理處",
						"ImagePath": "17_墾丁國家公園_社頂公園停車場_賣店",
						"ShowImage": "0.jpg",
						"Image": [ "1-11.jpg" ],
						"Image_360": [ "0.jpg" ],
						"Type": "build",
						"Position": "屏東",
						"Price": 1757,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "墾丁國家公園管理處石牛溪遊客中心警衛室新建工程",
						"Address":"屏東縣恆春鎮墾丁路596號",
						"Map":"墾丁國家公園遊客中心",
						"StartYear":  "78",
						"FinishYear":  "78",
						"Design":"",
						"Owner":"墾丁國家公園管理處",
						"ImagePath": "18_墾丁國家公園管理處石牛溪遊客中心警衛室新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-3.jpg" ],
						"Type": "build",
						"Position": "屏東",
						"Price": 129,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄宏法寺新建工程",
						"Address":"高雄市新興區仁愛一街302號",
						"Map":"宏法寺",
						"StartYear":  "78",
						"FinishYear":  "80",
						"Design":"永泰建築師事務所/有容室內設計",
						"Owner":"宏法寺",
						"ImagePath": "21_宏法寺新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-3.jpg" ],
						"Type": "build",
						"Position": "屏東",
						"Price": 1100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "中華電信嘉民機房新建工程",
						"Address":"台南市後壁區",
						"Map":"台南市後壁區",
						"StartYear":  "79",
						"FinishYear":  "79",
						"Design":"",
						"Owner":"中華電信",
						"ImagePath": "26_中華電信_嘉民機房新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-1.jpg" ],
						"Type": "build",
						"Position": "台南",
						"Price": 900,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄市灣機二號里集會所新建工程",
						"Address":"高雄市三民區壽昌路2號",
						"Map":"高雄市三民區壽昌路2號",
						"StartYear":  "80",
						"FinishYear":  "81",
						"Design":"",
						"Owner":"高雄市政府",
						"ImagePath": "29_灣機二號里集會所",
						"ShowImage": "0.jpg",
						"Image": [ "0-1.jpg" ],
						"Type": "build",
						"Position": "高雄",
						"Price": 3000,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "玉山國家公園管理處梅山服務中心一、二期工程",
						"Address":"高雄市桃源區梅山里梅山巷44-5號",
						"Map":"梅山遊客中心停車場一",
						"StartYear":  "80",
						"FinishYear":  "82",
						"Design":"陳開南建築師事務所",
						"Owner":"玉山國家公園管理處",
						"ImagePath": "30_玉山國家公園_梅山服務中心二期工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-2.jpg" ],
						"Type": "build",
						"Position": "高雄",
						"Price": 3000,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "墾丁國家公園鵝鑾鼻涼亭新建工程",
						"Address":"屏東縣恆春鎮鵝鑾里鵝鑾路301號",
						"Map":"鵝鑾鼻公園",
						"StartYear":  "80",
						"FinishYear":  "80",
						"Design":"李重耀建築師事務所",
						"Owner":"墾丁國家公園",
						"ImagePath": "32_墾丁國家公園鵝鸞鼻迎賓亭",
						"ShowImage": "0.jpg",
						"Image": [ "0.jpg" ],
						"Type": "wood",
						"Position": "屏東",
						"Price": 900,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "和風建設和風居新建工程",
						"Address":"高雄市前鎮區英德橫巷1弄19號",
						"Map":"高雄市前鎮區英德橫巷1弄19號",
						"StartYear":  "81",
						"FinishYear":  "82",
						"Design":"許文仁建築師事務所",
						"Owner":"和風建設",
						"ImagePath": "34_和風建設和風居",
						"ShowImage": "0.jpg",
						"Image": [ "0-3.jpg" ],
						"Type": "build",
						"Position": "高雄",
						"Price": 2000,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "彰化銀行九如路分行新購行舍內部裝修工程",
						"Address":"高雄市三民區九如二路7號",
						"Map":"彰化銀行 九如路分行",
						"StartYear":  "81",
						"FinishYear":  "81",
						"Design":"彰化銀行",
						"Owner":"彰化銀行",
						"ImagePath": "36_彰化銀行九如分行內部裝修",
						"ShowImage": "0.jpg",
						"Image": [ "0.jpg" ],
						"Type": "decoration",
						"Position": "高雄",
						"Price": 900,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "內政部營建署高雄都會公園日晷工程",
						"Address":"高雄市楠梓區德民路24號",
						"Map":"時間之鳥",
						"StartYear":  "83",
						"FinishYear":  "85",
						"Design":"許仲川建築師事務所",
						"Owner":"內政部營建署",
						"ImagePath": "47_內政部營建署高雄都會公園日晷工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-15.jpg" ],
						"Type": "landscape",
						"Position": "高雄",
						"Price": 1089,
						"Wonderful": "yes",
						"Display": "true"
					},
					
					{
						"Name":  "高雄縣勞工育樂中心(第三期)裝修工程",
						"Address":"高雄市鳥松區大埤路117號",
						"Map":"澄清會館 - 高雄市政府勞工局",
						"StartYear":  "83",
						"FinishYear":  "84",
						"Design":"禾耘建築師事務所",
						"Owner":"高雄縣政府",
						"ImagePath": "52_高雄縣勞工育樂中心裝修工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-6.jpg" ],
						"Type": "decoration",
						"Position": "高雄",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄縣縣立體育館整修工程",
						"Address":"高雄市鳳山區體育路65號",
						"Map":"鳳山體育館",
						"StartYear":  "84",
						"FinishYear":  "85",
						"Design":"潘忠明建築師事務所",
						"Owner":"高雄縣政府",
						"ImagePath": "67_高雄縣縣立體育館裝修工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-3.jpg" ],
						"Type": ["build","decoration"],
						"Position": "高雄",
						"Price": 1500,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "台南妙心寺文教大樓新建工程",
						"Address":"台灣台南市永康區勝利街11巷10號",
						"Map":"小東山妙心寺",
						"StartYear":  "85",
						"FinishYear":  "86",
						"Design":"王秀蓮建築師事務所",
						"Owner":"小東山妙心寺",
						"ImagePath": "71_妙心寺文教大樓新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-1.jpg" ],
						"Type": "build",
						"Position": "台南",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "世華銀行新興分行一樓裝修工程",
						"Address":"台灣高雄市新興區中正三路55號1樓",
						"Map":"國泰世華銀行 新興分行",
						"StartYear":  "85",
						"FinishYear":  "85",
						"Design":"環境設計有限公司",
						"Owner":"世華銀行",
						"ImagePath": "76_世華銀行新興分行內部裝修",
						"ShowImage": "0.jpg",
						"Image": [ "0.jpg" ],
						"Type": ["build","decoration"],
						"Position": "高雄",
						"Price": 900,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄銀行資訊大樓營建工程",
						"Address":"高雄市三民區九如一路520號",
						"Map":"高雄市三民區九如一路520號",
						"StartYear":  "85",
						"FinishYear":  "87",
						"Design":"蔡瑞益建築師事務所",
						"Owner":"高雄銀行",
						"ImagePath": "80_高雄銀行資訊大樓營建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-4.jpg" ],
						"Type": "build",
						"Position": "高雄",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "國立科學工藝博物館館圍牆大門人行道工程",
						"Address":"高雄市三民區九如一路720號",
						"Map":"國立科學工藝博物館",
						"StartYear":  "85",
						"FinishYear":  "86",
						"Design":"三門建築師事務所",
						"Owner":"國立科學工藝博物館",
						"ImagePath": "84_科工館人行道",
						"ShowImage": "0.jpg",
						"Image": [ "0-3.jpg" ],
						"Type": "landscape",
						"Position": "高雄",
						"Price": 900,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄市立小港醫院新建裝修工程",
						"Address":"高雄市小港區山明路482號",
						"Map":"小港醫院",
						"StartYear":  "86",
						"FinishYear":  "86",
						"Design":"禾耘建築師事務所",
						"Owner":"高雄市立小港醫院",
						"ImagePath": "87_高雄市立小港醫院新建裝修工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-5.jpg" ],
						"Type": ["build","decoration"],
						"Position": "高雄",
						"Price": 5100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "行政院衛生署朴子醫院擴建醫療大樓裝修工程",
						"Address":"嘉義縣朴子市永和里42-50號",
						"Map":"衛生福利部朴子醫院",
						"StartYear":  "86",
						"FinishYear":  "87",
						"Design":"陳怡良建築師事務所",
						"Owner":"行政院衛生署朴子醫院",
						"ImagePath": "89_台灣省立朴子醫院擴建醫療大樓後裝修工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-5.jpg" ],
						"Type": ["build","decoration"],
						"Position": "嘉義",
						"Price": 5100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "行政院衛生署南投醫院醫療大樓擴建第二期建築裝修工程",
						"Address":"南投縣南投市復興路478號",
						"Map":"衛生福利部南投醫院",
						"StartYear":  "87",
						"FinishYear":  "91",
						"Design":"唐真真建築師事務所",
						"Owner":"行政院衛生署南投醫院",
						"ImagePath": "93_行政院衛生署南投醫院醫療大樓擴建第二期建築裝修工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-12.jpg" ],
						"Type": ["build","decoration"],
						"Position": "南投",
						"Price": 20249,
						"Wonderful": "yes",
						"Display": "true"
					},
					
					{
						"Name":  "中華電信臺東電信服務中心新建工程",
						"Address":"台灣台東縣台東市大同路128號",
						"Map":"中華電信 台東服務中心",
						"StartYear":  "87",
						"FinishYear":  "89",
						"Design":"興興建築師事務所",
						"Owner":"中華電信",
						"ImagePath": "95_中華電信_台東電信服務中心",
						"ShowImage": "0.jpg",
						"Image": [ "0-15.jpg" ],
						"Type": "build",
						"Position": "台東",
						"Price": 11000,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄縣第三級古蹟鳳山縣城殘蹟修復工程",
						"Address":"高雄市鳳山區中山路5巷",
						"Map":"訓風砲台",
						"StartYear":  "87",
						"FinishYear":  "88",
						"Design":"李廣中建築師事務所",
						"Owner":"高雄縣政府",
						"ImagePath": "96_高雄縣第三級古蹟鳳山縣城殘跡修護工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-1.jpg" ],
						"Type": "historicSite",
						"Position": "高雄",
						"Price": 5100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄縣鳥松溼地公園工程",
						"Address":"高雄市鳥松區澄清湖大門口東側",
						"Map":"鳥松溼地公園",
						"StartYear":  "88",
						"FinishYear":  "89",
						"Design":"曠宇景觀工程顧問公司",
						"Owner":"高雄縣政府",
						"ImagePath": "101_高雄縣鳥松溼地公園工程",
						"ShowImage": "0.jpg",
						"Image": [ "2-56.jpg" ],
						"Image_360": [ "0-1.jpg" ],
						"Type": "landscape",
						"Position": "高雄",
						"Price": 4516,
						"Wonderful": "yes",
						"Display": "true"
					},
					
					{
						"Name":  "高雄縣桃源鄉原住民文物館新建工程",
						"Address":"高雄市桃源區南進巷180號",
						"Map":"高雄市桃源區原住民文化館",
						"StartYear":  "91",
						"FinishYear":  "92",
						"Design":"陳昇章建築師事務所",
						"Owner":"桃源鄉公所",
						"ImagePath": "106_桃源鄉原住民文物館新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-4.jpg" ],
						"Type": "build",
						"Position": "高雄",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄縣橋頭舊市區文化步道及辦公區公共景觀工程",
						"Address":"高雄市橋頭區隆豐路1號",
						"Map":"高雄市橋頭區公所",
						"StartYear":  "89",
						"FinishYear":  "90",
						"Design":"森環總合計畫集團",
						"Owner":"橋頭鄉公所",
						"ImagePath": "107_高雄縣橋頭舊市區文化步道及辦公區公共景觀工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-21.jpg" ],
						"Type": "landscape",
						"Position": "高雄",
						"Price": 1100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "嘉南農田水利會烏山頭風景區入口區親水公園(第二期)工程",
						"Address":"台南市官田區烏山頭里嘉南68-2號 ",
						"Map":"烏山頭水庫風景區旅客服務中心",
						"StartYear":  "89",
						"FinishYear":  "90",
						"Design":"冠欣工程顧問公司",
						"Owner":"嘉南農田水利會",
						"ImagePath": "109_烏山頭風景區入口區親水公園工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-8.jpg" ],
						"Type": "landscape",
						"Position": "台南",
						"Price": 5100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄縣美濃客家文物館第三期工程",
						"Address":"高雄市美濃區民族路49-3號",
						"Map":"美濃客家文物館 Meinong Hakka Cultural Museum",
						"StartYear":  "89",
						"FinishYear":  "89",
						"Design":"謝英俊建築師事務所/名匠設計裝潢工程有限公司",
						"Owner":"高雄縣政府",
						"ImagePath": "111_高雄縣美濃客家文物館第三期工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-7.jpg" ],
						"Type": "build",
						"Position": "高雄",
						"Price": 900,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "嘉義縣稅捐大樓週邊景觀工程",
						"Address":"嘉義縣太保市祥和二路東段5號",
						"Map":"嘉義縣財政稅務局",
						"StartYear":  "90",
						"FinishYear":  "90",
						"Design":"陳尚志建築師事務所",
						"Owner":"嘉義縣政府",
						"ImagePath": "114_嘉義縣稅捐大樓週邊景觀工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-3.jpg" ],
						"Type": "landscape",
						"Position": "嘉義",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "嘉義縣政府布袋遊艇港二期陸域工程",
						"Address":"嘉義縣布袋鎮新興街",
						"Map":"布袋遊艇港",
						"StartYear":  "92",
						"FinishYear":  "94",
						"Design":"戴台津建築師事務所",
						"Owner":"嘉義縣政府",
						"ImagePath": "115_嘉義縣政府布袋遊艇港二期陸域工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-1.jpg" ],
						"Type": "build",
						"Position": "嘉義",
						"Price": 5100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "台南科學園區一期大洲排水景觀及行人橋工程",
						"Address":"台南市新市區大順八路",
						"Map":"23.099839, 120.287246",
						"StartYear":  "90",
						"FinishYear":  "91",
						"Design":"漢明國際景觀有限公司",
						"Owner":"南部科學工業園區",
						"ImagePath": "116_台南科學園區一期大洲排水景觀及行人橋工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-7.jpg" ],
						"Type": "landscape",
						"Position": "台南",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "台電南部電廠第四號機廢水處理控制大樓新建工程",
						"Address":"高雄市前鎮區復興四路10號",
						"Map":"高雄市前鎮區復興四路10號",
						"StartYear":  "90",
						"FinishYear":  "91",
						"Design":"台灣電力股份有限公司",
						"Owner":"台灣電力股份有限公司",
						"ImagePath": "117_台電南部電廠第四機廢水處理控制大樓新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-1.jpg" ],
						"Type": "build",
						"Position": "高雄",
						"Price": 1100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄縣政府「廿一世紀大高雄花展」硬體工程",
						"Address":"高雄市鳳山區國泰路一段152號",
						"Map":"鳳山台糖假日花市",
						"StartYear":  "90",
						"FinishYear":  "90",
						"Design":"津魚企業有限公司",
						"Owner":"高雄市政府",
						"ImagePath": "119_二十一世紀大高雄花展硬體工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-7.jpg" ],
						"Type": ["build","landscape"],
						"Position": "高雄",
						"Price": 900,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "台電南部電廠第四號機T/G廠房建築裝修工程",
						"Address":"高雄市前鎮區復興四路10號",
						"Map":"高雄市前鎮區復興四路10號",
						"StartYear":  "90",
						"FinishYear":  "91",
						"Design":"吉興工程顧問股份有限公司",
						"Owner":"台灣電力股份有限公司",
						"ImagePath": "120_台電南部電廠第四號機TG廠房建築裝修工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-5.jpg" ],
						"Type": "build",
						"Position": "高雄",
						"Price": 1100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄市政府鼓山九十年哨船頭旁公園(第二期)開闢工程",
						"Address":"鼓山區哨船街與安船街交叉路口",
						"Map":"哨船頭公園",
						"StartYear":  "90",
						"FinishYear":  "91",
						"Design":"固碁設計工程公司",
						"Owner":"高雄市政府養工處",
						"ImagePath": "121_鼓山哨船頭公園",
						"ShowImage": "0.jpg",
						"Image": [ "0-27.jpg" ],
						"Type": ["build","landscape"],
						"Position": "高雄",
						"Price": 1100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "海洋技術學院旗津校區教學大樓內部裝修及環境景觀工程",
						"Address":"高雄市旗津區中洲三路482號",
						"Map":"高雄科技大學 旗津校區",
						"StartYear":  "91",
						"FinishYear":  "91",
						"Design":"錢紹明建築師事務所",
						"Owner":"海洋技術學院",
						"ImagePath": "123_高雄海洋學院教學大樓內部裝修及環境景觀工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-5.jpg" ],
						"Type": ["plant","landscape"],
						"Position": "高雄",
						"Price": 5100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "屏東東發製藥鋼骨廠房工程",
						"Address":"屏東市工業區工業六路5號",
						"Map":"東發生物科技製藥股份有限公司",
						"StartYear":  "91",
						"FinishYear":  "92",
						"Design":"漢唐景觀建築師事務所",
						"Owner":"東發製藥廠股份有限公司",
						"ImagePath": "126_東發製藥鋼骨廠房工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-7.jpg" ],
						"Type": "plant",
						"Position": "屏東",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄市政府凹仔底原生植物園整建工程",
						"Address":"高雄市左營區重光路",
						"Map":"台灣高雄市左營區重光路原生植物園",
						"StartYear":  "92",
						"FinishYear":  "92",
						"Design":"郭書勝建築師事務所",
						"Owner":"高雄市政府養工處",
						"ImagePath": "127_高雄市凹仔底原生植物園整建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-37.jpg" ],
						"Type": "landscape",
						"Position": "高雄",
						"Price": 4122,
						"Wonderful": "yes",
						"Display": "true"
					},
					
					{
						"Name":  "衛生署嘉南療養院92年度綠色廳舍改善工程統包案",
						"Address":"台南市仁德區裕忠路539號",
						"Map":"衛生福利部嘉南療養院",
						"StartYear":  "92",
						"FinishYear":  "92",
						"Design":"黃文杰建築師事務所",
						"Owner":"嘉南療養院",
						"ImagePath": "134_行政院衛生署嘉南療養院綠色廳舍改善工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-59.jpg" ],
						"Type": ["build","landscape"],
						"Position": "台南",
						"Price": 1100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "澎湖技術學院體育館暨學生活動中心內部設施工程",
						"Address":"澎湖縣馬公市六合路300號",
						"Map":"國立澎湖科技大學",
						"StartYear":  "92",
						"FinishYear":  "92",
						"Design":"楊炳國建築師事務所",
						"Owner":"澎湖技術學院",
						"ImagePath": "135_澎湖技術學院體育館暨學生活動中心內部設施工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-2.jpg" ],
						"Type": ["plant","sport"],
						"Position": "澎湖",
						"Price": 1100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "台東新興國小91年度綠校園改造工程統包案",
						"Address":"台東縣金峰鄉金峰鄉新興村1鄰1號",
						"Map":"台東縣金峰鄉新興國民小學",
						"StartYear":  "92",
						"FinishYear":  "93",
						"Design":"沈芷蓀建築師事務所",
						"Owner":"台東新興國小",
						"ImagePath": "139_台東新興國小綠校園改造工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-23.jpg" ],
						"Type": "landscape",
						"Position": "台東",
						"Price": 1100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "嘉義縣立文化中心演藝廳第三期戶外表演廣場工程",
						"Address":"嘉義縣民雄鄉建國路二段265號",
						"Map":"嘉義縣表演藝術中心",
						"StartYear":  "92",
						"FinishYear":  "93",
						"Design":"黃永沃建築師事務所",
						"Owner":"嘉義縣政府",
						"ImagePath": "141_嘉義縣立文化中心戶外表演廣場工程",
						"ShowImage": "0.jpg",
						"Banner": [ "0-1.jpg" ],
						"Image": [ "0-18.jpg" ],
						"Type": "landscape",
						"Position": "嘉義",
						"Price": 4097,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄縣仁武鄉運動公園第一期興建工程",
						"Address":"高雄市仁武區(鳳仁路、水管路路口)",
						"Map":"仁武運動公園",
						"StartYear":  "93",
						"FinishYear":  "94",
						"Design":"造璟景觀設計有限公司",
						"Owner":"仁武鄉公所",
						"ImagePath": "144_仁武鄉運動公園第一期興建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-11.jpg" ],
						"Type": "landscape",
						"Position": "高雄",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄市政府海洋之星重要交通門戶環境改善工程(統包工程)",
						"Address":"高雄市苓雅區新光路底",
						"Map":"新光碼頭",
						"StartYear":  "94",
						"FinishYear":  "95",
						"Design":"李永欣建築師事務所/朱文明建築師事務所",
						"Owner":"高雄市政府新工處",
						"ImagePath": "145_高雄海洋之星重要交通門戶環境改善工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-15.jpg" ],
						"Type": "landscape",
						"Position": "高雄",
						"Price": 5100,
						"Wonderful": "yes",
						"Display": "true"
					},
					
					{
						"Name":  "高雄市政府94年度愛河沿岸(中都橋至中華路)美綠化工程-溼地生態營造工程",
						"Address":"高雄市三民區中都橋之中華路愛河沿岸",
						"Map":"中都愛河濕地公園",
						"StartYear":  "94",
						"FinishYear":  "95",
						"Design":"固碁設計工程有限公司，李嘉文建築師",
						"Owner":"高雄市政府養工處",
						"ImagePath": "146_愛河沿岸美綠化工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-12.jpg" ],
						"Type": "landscape",
						"Position": "高雄",
						"Price": 1360,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄市政府3號船渠東岸及11.12號碼頭開發工程",
						"Address":"高雄市鹽埕區公園二路",
						"Map":"高雄港11號碼頭",
						"StartYear":  "95",
						"FinishYear":  "95",
						"Design":"莊學能建築師事務所",
						"Owner":"高雄市政府新工處",
						"ImagePath": "148_3號船渠東岸及11_12號碼頭開發工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-17.jpg" ],
						"Type": ["build","landscape"],
						"Position": "高雄",
						"Price": 8000,
						"Wonderful": "yes",
						"Display": "true"
					},
					
					{
						"Name":  "澄清湖意象區公園改善、服務中心新建工程",
						"Address":"高雄市鳥松區澄清路856號",
						"Map":"蘊香庭蔬食戶外庭院餐飲",
						"StartYear":  "95",
						"FinishYear":  "96",
						"Design":"任森珂建築師事務所",
						"Owner":"慈香庭餐飲機構",
						"ImagePath": "149_澄清湖意象區公園改善服務中心新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-16.jpg" ],
						"Type": ["build","landscape"],
						"Position": "高雄",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄市政府95年度高雄市旗津區海岸路及廟前路等造街工程",
						"Address":"高雄市旗津區海岸路及廟前路",
						"Map":"海岸路 & 廟前路",
						"StartYear":  "95",
						"FinishYear":  "95",
						"Design":"翊祥建築師事務所",
						"Owner":"高雄市政府養工處",
						"ImagePath": "150_高雄市旗津區海岸路及廟前路等造街工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-23.jpg" ],
						"Type": "landscape",
						"Position": "高雄",
						"Price": 1100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "佛光山私立均頭國民中學行政大樓新建及全校景觀工程",
						"Address":"南投縣埔里鎮水頭路48號",
						"Map":"佛光山均頭國民中小學",
						"StartYear":  "95",
						"FinishYear":  "96",
						"Design":"黃明威建築師事務所、人境工程技術顧問有限公司",
						"Owner":"佛光山均頭國中",
						"ImagePath": "153_佛光山均頭國中小行政中心新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-47.jpg" ],
						"Type": ["build","landscape"],
						"Position": "南投",
						"Price": 5100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "台電台北中央調度中心裝修工程(第一期)及高雄中央調度中心裝修工程",
						"Address":"台北市中正區羅斯福路三段242號/高雄市三民區十全路中華路口",
						"Map":"台北市中正區羅斯福路三段242號",
						"StartYear":  "96",
						"FinishYear":  "97",
						"Design":"台灣電力股份有限公司",
						"Owner":"台灣電力股份有限公司",
						"ImagePath": "156_台北中央調度中心及高雄中央調度中心",
						"ShowImage": "0.jpg",
						"Image": [ "0-3.jpg" ],
						"Type": "plant",
						"Position": "台北",
						"Price": 5100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "雲嘉南風管處布袋多功能遊客中心整建工程",
						"Address":"嘉義縣布袋鎮",
						"Map":"布袋遊客中心",
						"StartYear":  "96",
						"FinishYear":  "97",
						"Design":"陳文祥建築師事務所",
						"Owner":"交通部雲嘉南濱海風管處",
						"ImagePath": "157_雲嘉南風管處布袋多功能遊客中心整建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-1.jpg" ],
						"Type": "build",
						"Position": "嘉義",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "屏東縣政府下淡水溪鐵橋-屏東端周邊整體開發工程",
						"Address":"屏東縣屏東市九曲路",
						"Map":"下淡水溪鐵橋",
						"StartYear":  "97",
						"FinishYear":  "97",
						"Design":"九河工程顧問有限公司",
						"Owner":"屏東縣政府水利處",
						"ImagePath": "159_屏東縣政府下淡水溪鐵橋_屏東端周邊整體開發工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-2.jpg" ],
						"Type": "landscape",
						"Position": "屏東",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄市政府2009世運場館陽明溜冰場整修工程",
						"Address":"高雄市三民區義華路168號",
						"Map":"高雄市三民區義華路168號",
						"StartYear":  "97",
						"FinishYear":  "97",
						"Design":"李永欣建築師事務所",
						"Owner":"高雄市政府新工處",
						"ImagePath": "161_世運場館陽明溜冰場整修工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-5.jpg" ],
						"Type": "sport",
						"Position": "高雄",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "日月潭風管處向山行政中心新建工程",
						"Address":"南投縣魚池鄉水社村中山路599號",
						"Map":"向山行政暨遊客中心",
						"StartYear":  "97",
						"FinishYear":  "98",
						"Design":"蘇懋彬建築師事務所",
						"Owner":"交通部觀光局日管處",
						"ImagePath": "163_日月潭國家風景區管理處向山行政中心新建工程",
						"Banner": [ "0-6.jpg" ],
						"ShowImage": [ "0.jpg" ],
						"Image": [ "0-138.jpg" ],
						"Image_360": [ "139-142.jpg" ],
						"Type": ["build", "landscape", "greenbuild"],
						"Position": "南投",
						"Price": 11000,
						"Wonderful": "yes",
						"Display": "true"
					},
					
					{
						"Name":  "佛光山弘法廣場南側邊坡整治工程",
						"Address":"高雄市大樹區統嶺路1號",
						"Map":"佛光山佛陀紀念館 Fo Guang Shan Buddha Museum",
						"StartYear":  "97",
						"FinishYear":  "98",
						"Design":"無",
						"Owner":"佛光山寺財團法人人間文教基金會",
						"ImagePath": "164_佛光山佛陀紀念館邊坡加勁網工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-15.jpg" ],
						"Type": ["temple", "cement"],
						"Position": "高雄",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "法鼓山雲集寺寺廟新建工程",
						"Address":"台南市佳里區六安里六安街218號",
						"Map":"法鼓山雲集寺",
						"StartYear":  "98",
						"FinishYear":  "99",
						"Design":"吳夏雄建築師事務所",
						"Owner":"財團法人法鼓山佛教基金會",
						"ImagePath": "165_法鼓山雲集寺",
						"ShowImage": "0.jpg",
						"Image": [ "0-19.jpg" ],
						"Type": "temple",
						"Position": "台南",
						"Price": 5985,
						"Wonderful": "yes",
						"Display": "true"
					},
					
					{
						"Name":  "屏東縣文化中心設施整建工程",
						"Address":"屏東縣屏東市和平路427號",
						"Map":"屏東藝術館(中正藝術館)",
						"StartYear":  "99",
						"FinishYear":  "99",
						"Design":"李永欣建築師事務所",
						"Owner":"屏東縣政府",
						"ImagePath": "167_屏東縣文化設施整建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-17.jpg" ],
						"Type": "decoration",
						"Position": "屏東",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "嘉義市文化中心整建計畫工程",
						"Address":"嘉義市忠孝路275號",
						"Map":"嘉義市立文化園區",
						"StartYear":  "99",
						"FinishYear":  "99",
						"Design":"許家彰建築師事務所",
						"Owner":"嘉義市政府文化局",
						"ImagePath": "168_嘉義市文化中心整建計劃工程",
						"ShowImage": "0.jpg",
						"Banner": [ "0-3.jpg" ],
						"Image": [ "1-45.jpg" ],
						"Image_360": [ "0.jpg" ],
						"Type": "decoration",
						"Position": "嘉義",
						"Price": 9441,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "奇美實業 #25電氣機電室新建工程",
						"Address":"台南市仁德區三甲里59-1號",
						"Map":"奇美實業股份有限公司",
						"StartYear":  "99",
						"FinishYear":  "100",
						"Design":"茂喬建築師事務所",
						"Owner":"奇美實業股份有限公司",
						"ImagePath": "169_奇美實業電器機電室新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-2.jpg" ],
						"Type": ["build", "plant"],
						"Position": "台南",
						"Price": 1100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "天主教真福山社福園區第一期環境改善工程",
						"Address":"高雄市杉林區合森巷160號",
						"Map":"天主教真福山社福文教中心",
						"StartYear":  "99",
						"FinishYear":  "100",
						"Design":"綠水規劃設計顧問有限公司",
						"Owner":"天主教會高雄教區",
						"ImagePath": "172_天主教真福山",
						"ShowImage": "0.jpg",
						"Image": [ "0-1.jpg" ],
						"Type": "landscape",
						"Position": "高雄",
						"Price": 900,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "林務局阿里山第一管制站區景觀改善工程",
						"Address":"林務局阿里山第一管制站",
						"Map":"行政院農業委員會林務局嘉義林區管理處阿里山遊樂區第一管制站",
						"StartYear":  "99",
						"FinishYear":  "101",
						"Design":"高而潘建築師事務所",
						"Owner":"行政院農委會林務局嘉義林區管理處",
						"ImagePath": "173_第一管制站區景觀改善工程",
						"ShowImage": "0.jpg",
						"Image": [ "2-66.jpg" ],
						"Image_360": [ "0-1.jpg" ],
						"Image_Description": [ 
												"0.jpg_石階造型\n具有藝術感",
												"1.jpg_雲霧繚繞的管制站，看起來很有意境\n這是從後方拍攝"],
						"Type": ["landscape", "wood"],
						"Position": "嘉義",
						"Price": 2614,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄縣六龜鄉新開部落(新發村)罹難者紀念公園工程",
						"Address":"高雄市六龜區舊新發國小新開分校原址",
						"Map":"新開紀念公園",
						"StartYear":  "100",
						"FinishYear":  "100",
						"Design":"九河工程顧問有限公司",
						"Owner":"高雄市文化局",
						"ImagePath": "174_新開部落罹難者紀念公園工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-21.jpg" ],
						"Type": "landscape",
						"Position": "高雄",
						"Price": 3934,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "國立成功大學醫學院附設醫院「急重症醫療區整建工程」",
						"Address":"台南市北區勝利路138號",
						"Map":"成功大學醫學院附設醫院",
						"StartYear":  "100",
						"FinishYear":  "101",
						"Design":"許常吉建築師事務所",
						"Owner":"國立成功大學",
						"ImagePath": "175_成大醫院急重症醫療區整建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-5.jpg" ],
						"Type": ["build", "decoration"],
						"Position": "台南",
						"Price": 11000,
						"Wonderful": "yes",
						"Display": "true"
					},
					
					{
						"Name":  "法鼓山「高雄市桃源區樂樂段永久屋住宅新建工程」",
						"Address":"高雄市桃源區樂樂段",
						"Map":"23.110750, 120.711089",
						"StartYear":  "100",
						"FinishYear":  "100",
						"Design":"徐伯瑞建築師事務所",
						"Owner":"財團法人法鼓山社會福利慈善事業基金會",
						"ImagePath": "176_法鼓山_高雄市桃源區樂樂段永久屋住宅新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "1-12.jpg" ],
						"Image_360": [ "0.jpg" ],
						"Type": ["build", "decoration"],
						"Position": "高雄",
						"Price": 4616,
						"Wonderful": "yes",
						"Display": "true"
					},
					
					{
						"Name":  "法鼓山「高雄市六龜區龍興段永久屋住宅新建工程」",
						"Address":"高雄市六龜區龍興段",
						"Map":"龍興永久屋(高雄市,永久屋,高雄市政府)",
						"StartYear":  "100",
						"FinishYear":  "100",
						"Design":"呂大吉建築師事務所",
						"Owner":"財團法人法鼓山社會福利慈善事業基金會",
						"ImagePath": "177_法鼓山龍興段永久屋住宅新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-14.jpg" ],
						"Type": ["build", "decoration"],
						"Position": "高雄",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "第一商業銀行「三民分行行舍新建工程(建築工程)」",
						"Address":"高雄市三民區中華三路291號",
						"Map":"高雄市三民區中華三路291號",
						"StartYear":  "100",
						"FinishYear":  "102",
						"Design":"譚俊彥建築師事務所",
						"Owner":"第一商業銀行股份有限公司",
						"ImagePath": "178_第一商業銀行_三民分行行舍新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-20.jpg" ],
						"Type": "build",
						"Position": "高雄",
						"Price": 7520,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "三聯科技本洲工業區廠房及辦公室新建工程",
						"Address":"高雄市本工六路17號",
						"Map":"三聯科技股份有限公司",
						"StartYear":  "101",
						"FinishYear":  "102",
						"Design":"陳昇章建築師事務所",
						"Owner":"三聯科技股份有限公司",
						"ImagePath": "182_三聯科技本洲工業區廠房及辦公室新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-5.jpg" ],
						"Type": ["build", "plant"],
						"Position": "高雄",
						"Price": 5100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "李春錦自用農舍新建工程",
						"Address":"嘉義市西區文化路722巷201號",
						"Map":"嘉義市西區文化路722巷",
						"StartYear":  "101",
						"FinishYear":  "102",
						"Design":"李永欣建築師事務所",
						"Owner":"李春錦",
						"ImagePath": "184_李春錦自用農舍新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-2.jpg" ],
						"Type": "build",
						"Position": "嘉義",
						"Price": 1100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "吉的堡幼兒園新建工程",
						"Address":"高雄市三民區光武路",
						"Map":"高雄市吉的堡金恩幼兒園",
						"StartYear":  "102",
						"FinishYear":  "102",
						"Design":"傅兆維建築師事務所",
						"Owner":"吉的堡網路科技股份有限公司",
						"ImagePath": "186_吉的堡幼兒園新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-6.jpg" ],
						"Type": "build",
						"Position": "高雄",
						"Price": 2804,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "莫拉克颱風災後長期安置住宅重建桃源區樂樂段基地（公共設施）計畫後續工程",
						"Address":"高雄市桃源區樂樂段",
						"Map":"23.113049,120.710134",
						"StartYear":  "102",
						"FinishYear":  "103",
						"Design":"徐伯瑞建築師事務所",
						"Owner":"高雄市政府水利局",
						"ImagePath": "187_莫拉克颱風災後長期安置住宅重建桃源區樂樂段基地",
						"ShowImage": "0.jpg",
						"Image": [ "1-12.jpg" ],
						"Image_360": [ "0.jpg" ],
						"Type": ["build", "landscape", "sport"],
						"Position": "高雄",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "日月潭教師會館迎賓樓重建暨周邊景觀改善工程",
						"Address":"南投縣魚池鄉中興路136號",
						"Map":"日月潭教師會館",
						"StartYear":  "102",
						"FinishYear":  "104",
						"Design":"游道生建築師事務所",
						"Owner":"日月潭教師會館",
						"ImagePath": "190_日月潭教師會館",
						"ShowImage": "0.jpg",
						"Image": [ "0-12.jpg" ],
						"Type": ["build", "landscape", "decoration"],
						"Position": "南投",
						"Price": 11000,
						"Wonderful": "yes",
						"Display": "true"
					},
					
					{
						"Name":  "高雄市水利局鹽埕區南北大溝抽水站工程",
						"Address":"高雄市鹽埕區必信街",
						"Map":"高雄市鹽埕區必信街",
						"StartYear":  "102",
						"FinishYear":  "103",
						"Design":"黎明工程顧問股份有限公司",
						"Owner":"高雄市政府",
						"ImagePath": "188_高雄市水利局鹽埕區南北大溝抽水站工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-3.jpg" ],
						"Type": "build",
						"Position": "高雄",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "奇美實業股份有限公司 PRP研發大樓土建工程",
						"Address":"台南市新市區王甲路180號",
						"Map":"奇美實業股份有限公司特化廠",
						"StartYear":  "102",
						"FinishYear":  "104",
						"Design":"吳俊賢建築師事務所",
						"Owner":"奇美實業股份有限公司",
						"ImagePath": "191_奇美實業特化廠區新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-9.jpg" ],
						"Type": "build",
						"Position": "台南",
						"Price": 11000,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "實踐大學 台北校區C、G棟整建工程案",
						"Address":"台北市中山區大直街70號",
						"Map":"實踐大學 臺北校區",
						"StartYear":  "103",
						"FinishYear":  "104",
						"Design":"蘇富源建築師事務所",
						"Owner":"實踐大學",
						"ImagePath": "192_實踐大學台北校區CG棟",
						"ShowImage": "0.jpg",
						"Image": [ "0-30.jpg" ],
						"Type": "build",
						"Position": "台北",
						"Price": 5100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "財團法人創世社會福利基金會苗栗社教中心新建工程",
						"Address":"苗栗縣頭屋鄉茄苳段478地號土地",
						"Map":"24.592361,120.886056",
						"StartYear":  "104",
						"FinishYear":  "106",
						"Design":"大冶建築師事務所",
						"Owner":"創世社會基金會",
						"ImagePath": "193_創世基金會苗栗社教中心",
						"ShowImage": "0.jpg",
						"Image": [ "0-7.jpg" ],
						"Type": "build",
						"Position": "苗栗",
						"Price": 5100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "馬偕紀念醫院台東分院平安樓1-3樓整建工程",
						"Address":"台東縣台東市長沙街303巷1號",
						"Map":"台東馬偕紀念醫院",
						"StartYear":  "104",
						"FinishYear":  "105",
						"Design":"譚俊彥建築師事務所",
						"Owner":"馬偕醫院",
						"ImagePath": "194_馬偕紀念醫院台東分院",
						"ShowImage": "0.jpg",
						"Image": [ "0-13.jpg" ],
						"Type": "decoration",
						"Position": "台東",
						"Price": 5100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "當得開發科技股份有限公司廠房新建工程",
						"Address":"嘉義縣大林鎮大工一段41-1地號土地",
						"Map":"23.597745, 120.509676",
						"StartYear":  "104",
						"FinishYear":  "106",
						"Design":"許英毅建築師事務所",
						"Owner":"當得開發科技股份有限公司",
						"ImagePath": "195_當得開發科技廠房",
						"ShowImage": "0.jpg",
						"Image": [ "1-26.jpg" ],
						"Image_360": [ "0.jpg" ],
						"Type": ["build", "plant"],
						"Position": "嘉義",
						"Price": 8750,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "華南商業銀行「左營分行行舍裝修工程」",
						"Address":"高雄市左營區博愛四路166號",
						"Map":"華南銀行 左營分行",
						"StartYear":  "105",
						"FinishYear":  "105",
						"Design":"頡合設計",
						"Owner":"華南商業銀行",
						"ImagePath": "199_華南銀行左營分行行舍裝修工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-4.jpg" ],
						"Type": "decoration",
						"Position": "高雄",
						"Price": 900,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "古坑鄉崁腳段同心苑住宅新建工程",
						"Address":"雲林縣古坑鄉崁腳段95地號",
						"Map":"古坑",
						"StartYear":  "106",
						"FinishYear":  "工程階段",
						"Design":"朱文明建築師事務所",
						"Owner":"李○○等62位",
						"ImagePath": "198_古坑鄉崁腳段同心苑住宅新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-11.jpg" ],
						"Type": ["build", "landscape", "decoration"],
						"Position": "雲林",
						"Price": 11000,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "利瑪竇大樓整建工程",
						"Address":"新北市輔仁大學校區內",
						"Map":"輔仁大學利瑪竇大樓",
						"StartYear":  "106",
						"FinishYear":  "106",
						"Design":"許明義建築師事務所",
						"Owner":"輔仁大學學校財團法人輔仁大學",
						"ImagePath": "196_輔大利瑪竇外牆整建",
						"ShowImage": "0.jpg",
						"Image": [ "0-3.jpg" ],
						"Type": ["build", "decoration"],
						"Position": "台北",
						"Price": 1100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "高雄市81氣爆紀念裝置藝術計畫",
						"Address":"高雄市立五權國小(臨三多路及凱旋路側)",
						"Map":"高雄市五權國小",
						"StartYear":  "106",
						"FinishYear":  "107",
						"Design":"黃明威建築師事務所",
						"Owner":"高雄市政府文化局",
						"ImagePath": "197_高雄市81氣爆紀念裝置藝術計畫",
						"ShowImage": "0.jpg",
						"Image": [ "0-12.jpg" ],
						"Image_Video": [ "wb6bd14IR3I" ],
						"Type": ["build", "landscape"],
						"Position": "高雄",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "台南市北區婞芙產後護理之家新建及室內裝修工程",
						"Address":"台南市北區文成一路208號",
						"Map":"婞芙產後護理之家",
						"StartYear":  "107",
						"FinishYear":  "109",
						"Design":"徐岩奇建築師事務所",
						"Owner":"康芙國際有限公司",
						"ImagePath": "203_婞芙產後護理之家室內裝修工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-33.jpg" ],
						"Type": ["build", "decoration"],
						"Position": "台南",
						"Price": 11000,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "毅超砂布紙廠房新建工程",
						"Address":"高雄市大寮區和業八路",
						"Map":"xx",
						"StartYear":  "108",
						"FinishYear":  "109",
						"Design":"李永欣建築師事務所",
						"Owner":"毅超砂布紙有限公司",
						"ImagePath": "00_xxx",
						"ShowImage": "0.jpg",
						"Image": [ "0-3.jpg" ],
						"Type": ["build", "plant"],
						"Position": "高雄",
						"Price": 2600,
						"Wonderful": "no",
						"Display": "false"
					},
					
					{
						"Name":  "古坑鄉崁腳段同心別苑住宅新建工程",
						"Address":"雲林縣古坑鄉崁腳段95地號",
						"Map":"古坑",
						"StartYear":  "108",
						"FinishYear":  "工程階段",
						"Design":"朱文明建築師事務所",
						"Owner":"李○○等62位",
						"ImagePath": "195_古坑鄉崁腳段同心苑住宅新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-8.jpg" ],
						"Type": ["build", "decoration"],
						"Position": "雲林",
						"Price": 1100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "臺中市環保節能減碳館新建工程",
						"Address":"台中市西屯區西大墩公園內",
						"Map":"西大墩公園",
						"StartYear":  "109",
						"FinishYear":  "工程階段",
						"Design":"徐伯瑞建築師事務所",
						"Owner":"財團法人文英基金會/台中市政府",
						"ImagePath": "201_臺中市環保節能減碳館新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-5.jpg" ],
						"Type": ["landscape", "greenbuild"],
						"Position": "臺中",
						"Price": 5100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "奇美物流廠改建重櫃場－球場拆除及增設工程",
						"Address":"台南市奇美實業物流廠",
						"Map":"台南市奇美實業物流廠",
						"StartYear":  "109",
						"FinishYear":  "109",
						"Design":"吳俊賢建築師事務所",
						"Owner":"奇美實業股份有限公司",
						"ImagePath": "202_奇美物流廠改建重櫃場－球場拆除及增設工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-1.jpg" ],
						"Type": "plant",
						"Position": "台南",
						"Price": 1100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "奇美PC倉庫群整合工程-W庫Revamping工程",
						"Address":"台南市仁德區開發四路22號",
						"Map":"台南市仁德區開發四路22號",
						"StartYear":  "109",
						"FinishYear":  "110",
						"Design":"吳俊賢建築師事務所",
						"Owner":"奇美實業股份有限公司",
						"ImagePath": "204_奇美PC倉庫群整合工程-W庫Revamping工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-14.jpg" ],
						"Type": "plant",
						"Position": "台南",
						"Price": 5100,
						"Wonderful": "no",
						"Display": "true"
					},
					
					{
						"Name":  "福智佛教學院圖書行政資訊大樓新建工程",
						"Address":"雲林縣古坑鄉麻園村平和25號",
						"Map":"雲林縣古坑鄉麻園村平和25號",
						"StartYear":  "110",
						"FinishYear":  "112",
						"Design":"大藏聯合建築師事務所",
						"Owner":"福智學校財團法人",
						"ImagePath": "205_福智佛教學院圖書行政資訊大樓新建工程",
						"ShowImage": "0.jpg",
						"Image": [ "0-88.jpg" ],
						"Type": "build",
						"Position": "南投",
						"Price": 36868,
						"Wonderful": "yes",
						"Display": "true"
					},
					
					{
						"Name":  "高雄必信街倉庫結構補強工程",
						"Address":"高雄市鹽埕區必信街內",
						"Map":"高雄市鹽埕區必信街內",
						"StartYear":  "109",
						"FinishYear":  "工程階段",
						"Design":"安誠工程技術顧問有限公司",
						"Owner":"第一商業銀行股份有限公司",
						"ImagePath": "00_xxx",
						"ShowImage": "0.jpg",
						"Image": [ "0-3.jpg" ],
						"Type": "build",
						"Position": "高雄",
						"Price": 1100,
						"Wonderful": "no",
						"Display": "false"
					},
					
					{
						"Name":  "台聚高值化研發實驗室主體工程",
						"Address":"高雄市大社區永宏巷內",
						"Map":"高雄市大社區永宏巷內",
						"StartYear":  "110",
						"FinishYear":  "工程階段",
						"Design":"王曉奎建築師事務所",
						"Owner":"台灣聚合化學品股份有限公司",
						"ImagePath": "00_xxx",
						"ShowImage": "0.jpg",
						"Image": [ "0-3.jpg" ],
						"Type": "plant",
						"Position": "高雄",
						"Price": 11000,
						"Wonderful": "no",
						"Display": "false"
					}					
					
				]

};